name: Fetch Threat Intel Sources

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  fetch_and_clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Files
        run: |
          curl -s -o hosts.txt https://raw.githubusercontent.com/Zaczero/pihole-phishtank/refs/heads/main/hosts.txt
          curl -s -o phishing-domains-ACTIVE.txt https://raw.githubusercontent.com/Phishing-Database/Phishing.Database/refs/heads/master/phishing-domains-ACTIVE.txt

      - name: Clean Files
        run: |
          cat hosts.txt phishing-domains-ACTIVE.txt | grep -vE '^\s*#|^\s*$|redacted' > Malicious_URLs/external_urls

      - name: Commit Changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add Malicious_URLs/external_urls
          git commit -m "Update external URLs" || echo "No changes to commit"
          git push
